source 'https://rubygems.org'

# Bundle edge Rails instead: gem 'rails', github: 'rails/rails'
gem 'rails', '4.0.8'

# Use mysql as the database for Active Record
gem 'mysql2'

gem 'active_model_serializers'

group :development, :test do
  gem 'sqlite3'
end

group :production do
  gem 'mysql'
end


group :doc do
  gem 'sdoc', require: false
end

